import fs from 'fs';
import puppeteer from 'puppeteer';
import path from 'path';
const browser = await puppeteer.launch({ headless: 'new', protocolTimeout: 900000,
  args: ['--no-sandbox','--disable-setuid-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 560, height: 315 });
page.setDefaultTimeout(900000); page.setDefaultNavigationTimeout(900000);
await page.goto('file://' + path.resolve('dist/aetherfall.html') + '?qa=1', { waitUntil: 'domcontentloaded' });
await new Promise(r => setTimeout(r, 7000));
await page.evaluate(() => document.getElementById('btn-begin').click());
await page.evaluate((k) => window.__pump(k), 3);
await page.evaluate(() => { window.__teleport(14, -20); window.__look(Math.PI, 0.24); });
await page.evaluate((k) => window.__pump(k), 3);
await page.evaluate(() => { document.getElementById('settings').classList.remove('hidden'); });
await page.evaluate((k) => window.__pump(k), 2);
fs.mkdirSync('review', { recursive: true });
await page.screenshot({ path: 'review/ui-settings.png' });
console.log('ui shot ok');
await browser.close();
